version: '3'
services:
  postgres_db:
    build: ./.docker/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wawwd
      POSTGRES_USER: wawwd123
      POSTGRES_PASSWORD: wawwd456
      POSTGRES_HOST_AUTH_METHOD: trust
    hostname: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@wawwd.dev
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    depends_on:
      - postgres_db
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - LS_LOG=trace
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: redis:7.2.2-alpine
    volumes:
      - cache-data:/data
    ports:
      - "6379:6379"

volumes:
  db-data:
  pg-admin:
  cache-data: